name: .Net

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup .Net
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: 8.0.x

            - name: Build the solution
              run: dotnet build --no-restore --configuration Release

            - name: Install dependencies
              run: dotnet build --no-restore

            - name: Test
              run: dotnet test --no-build --verbosity normal