name: CI - Build and Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. 檢出代碼
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. 設置 .NET 環境
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0' # 根據您的專案版本

    # 3. 還原依賴項
    - name: Restore dependencies
      run: dotnet restore ./UnitTest.sln

    # 4. 構建主專案與測試專案
    - name: Build solution
      run: dotnet build ./UnitTest.sln --configuration Debug

    # 5. 執行 HWUnitTest 測試
    - name: Run HWUnitTest
      run: dotnet test HWUnitTest/HWUnitTest.csproj --no-build --verbosity normal

    # 6. 執行 XUnitTest 測試
    - name: Run XUnitTest
      run: dotnet test XUnitTest/XUnitTest.csproj --no-build --verbosity normal